FROM golang:alpine

WORKDIR /tool/ffuf

RUN go install github.com/ffuf/ffuf/v2@latest

RUN mv $GOPATH/bin/ffuf .

FROM alpine:latest

ENV PATH="$PATH:/tool"

WORKDIR ${PATH}

COPY --from=0 /tool/ffuf/ffuf /tool/ffuf

CMD ["ffuf"]