FROM golang:1.21-alpine3.18

WORKDIR /tool/gobuster

RUN go install github.com/OJ/gobuster/v3@latest

RUN mv $GOPATH/bin/gobuster .

FROM alpine:latest

ENV PATH="$PATH:/tool"

WORKDIR ${PATH}

COPY --from=0 /tool/gobuster/gobuster /tool/gobuster

CMD ["gobuster"]
             