FROM python:3.8-alpine3.12

RUN apk add --no-cache build-base curl-dev

WORKDIR /tool/paramspider

RUN apk add git

RUN git clone https://github.com/0xKayala/ParamSpider

WORKDIR /tool/paramspider/ParamSpider

RUN pip3 install -r requirements.txt

#CMD ["python paramspider.py"]
